/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import connect.ConnectDB;
import dao.ChiTietHD_DAO;
import dao.HoaDon_DAO;
import entity.ChiTietHD;

import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class HoaDon extends javax.swing.JPanel {

    private ChiTietHD_DAO chiTietHD_dao;
    private DefaultTableModel modelHoaDon;
    private DefaultTableModel modelChiTietHD;

    /**
     * Creates new form HoaDon
     */
    public HoaDon() {
        ConnectDB.getInstance().connect();
        initComponents();
        chiTietHD_dao = new ChiTietHD_DAO();

        ArrayList<ChiTietHD> cthd = chiTietHD_dao.getAllOrder();
        loadData(new HoaDon_DAO().getAllOrder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane_HoaDon = new javax.swing.JTabbedPane();
        HoaDonPhaChe = new javax.swing.JPanel();
        HoaDon_lbl = new javax.swing.JLabel();
        scrollPane_HoaDon = new javax.swing.JScrollPane();
        HoaDon_Table = new javax.swing.JTable();
        HoaDonChiTiet_lbl = new javax.swing.JLabel();
        jScrollPane_HoaDonChiTiet = new javax.swing.JScrollPane();
        HoaDonChiTiet_Table = new javax.swing.JTable();
        ThongTin1 = new javax.swing.JPanel();
        MaHoaDon1_lbl = new javax.swing.JLabel();
        MaHoaDon1_txt = new javax.swing.JTextField();
        KhachHang1_txt = new javax.swing.JTextField();
        KhachHang1_lbl = new javax.swing.JLabel();
        SoDienThoai1_lbl = new javax.swing.JLabel();
        ThoiGianTao1_txt = new javax.swing.JTextField();
        SoDienThoai1_txt = new javax.swing.JTextField();
        ThoiGianTao1_lbl = new javax.swing.JLabel();
        ThoiGianThanhToan1_lbl = new javax.swing.JLabel();
        LoaiThanhToan1_lbl = new javax.swing.JLabel();
        LoaiThanhToan1_txt = new javax.swing.JTextField();
        GhiChu1_lbl = new javax.swing.JLabel();
        scrollPaneGhiChu = new javax.swing.JScrollPane();
        GhiChu1_txt = new javax.swing.JTextArea();
        ThoiGianThanhToan1_txt = new javax.swing.JTextField();
        TrangThai1 = new javax.swing.JPanel();
        TrangThai1_lbl = new javax.swing.JLabel();
        TrangThaiStatus1_lbl = new javax.swing.JLabel();
        TongTienSanPham1_lbl = new javax.swing.JLabel();
        ChiTieuKhac1_lbl = new javax.swing.JLabel();
        TongTienHoaDon1_lbl = new javax.swing.JLabel();
        DiaChi1_lbl = new javax.swing.JLabel();
        scrollPaneDiaChi = new javax.swing.JScrollPane();
        DiaChi1_txt = new javax.swing.JTextArea();
        TongTienSanPham1_txt = new javax.swing.JTextField();
        ChiTietKhac1_txt = new javax.swing.JTextField();
        TongTienHoaDon1_txt = new javax.swing.JTextField();
        XacNhan_Button = new javax.swing.JButton();
        LichSuHoaDon = new javax.swing.JPanel();
        MaHoaDon2_lbl = new javax.swing.JLabel();
        MaHoaDon2_txt = new javax.swing.JTextField();
        Tim = new javax.swing.JButton();
        TuNgay_lbl = new javax.swing.JLabel();
        DenNgay_lbl = new javax.swing.JLabel();
        TrangThai2_lbl = new javax.swing.JLabel();
        cbb_TrangThai = new javax.swing.JComboBox<>();
        Loc_Button = new javax.swing.JButton();
        scrollPaneHoaDon_LichSuHD = new javax.swing.JScrollPane();
        HoaDonInfo_Table = new javax.swing.JTable();
        ChiTietHoaDon = new javax.swing.JLabel();
        scrollPaneChiTietHoaDon = new javax.swing.JScrollPane();
        jTableChiTietHD = new javax.swing.JTable();
        ThongTin2 = new javax.swing.JPanel();
        lblMaHoaDon = new javax.swing.JLabel();
        txtMaHoaDon_LichSuHD = new javax.swing.JTextField();
        txtKhachHang_LichSuHD = new javax.swing.JTextField();
        lblKhachHang = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        txtThoiGianTao_LichSuHD = new javax.swing.JTextField();
        txtSoDienThoai_LichSuHD = new javax.swing.JTextField();
        lblThoiGianTao = new javax.swing.JLabel();
        lblThoiGianThanhToan = new javax.swing.JLabel();
        lblLoaiThanhToan = new javax.swing.JLabel();
        txtLoaiThanhToan_LichSuHD = new javax.swing.JTextField();
        lblGhiChu = new javax.swing.JLabel();
        scrollPaneGhiChu_LichSuHD = new javax.swing.JScrollPane();
        textArea_GhiChu = new javax.swing.JTextArea();
        TrangThai2 = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblTrangThai_Status = new javax.swing.JLabel();
        lblTongTienSanPham = new javax.swing.JLabel();
        lblChiTieuKhac = new javax.swing.JLabel();
        lblTongTienHoaDon = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        scrollPaneDiaChi_LichSuHD = new javax.swing.JScrollPane();
        textArea_DiaChi = new javax.swing.JTextArea();
        txt_TongTienSP = new javax.swing.JTextField();
        txt_TongTienHD = new javax.swing.JTextField();
        txt_ChiTietKhac = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 238, 232));

        HoaDonPhaChe.setBackground(new java.awt.Color(250, 238, 232));

        HoaDon_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HoaDon_lbl.setText("Hóa đơn");
        HoaDon_lbl.setForeground(Color.black);
        HoaDon_lbl.setBackground(Color.white);

        HoaDon_Table.setRowHeight(25);
        HoaDon_Table.setForeground(Color.black);
        HoaDon_Table.setBackground(Color.WHITE);
        HoaDon_Table.setShowGrid(true);
        HoaDon_Table.setGridColor(Color.black);
        HoaDon_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Mã hóa đơn", "Người tạo", "Thời gian tạo", "Tổng tiền", "Trạng thái"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPane_HoaDon.setViewportView(HoaDon_Table);
        scrollPane_HoaDon.setBackground(Color.white);

        HoaDonChiTiet_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HoaDonChiTiet_lbl.setText("Hóa đơn chi tiết");
        HoaDonChiTiet_lbl.setBackground(Color.white);
        HoaDonChiTiet_lbl.setForeground(Color.black);

        HoaDonChiTiet_Table.setRowHeight(25);
        HoaDonChiTiet_Table.setForeground(Color.black);
        HoaDonChiTiet_Table.setBackground(Color.WHITE);
        HoaDonChiTiet_Table.setShowGrid(true);
        HoaDonChiTiet_Table.setGridColor(Color.black);
        HoaDonChiTiet_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        HoaDonChiTiet_Table.setShowVerticalLines(true);
        jScrollPane_HoaDonChiTiet.setViewportView(HoaDonChiTiet_Table);
        jScrollPane_HoaDonChiTiet.setBackground(Color.white);

        ThongTin1.setBackground(new java.awt.Color(250, 238, 232));

        MaHoaDon1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaHoaDon1_lbl.setText("Mã hóa đơn:");
        MaHoaDon1_lbl.setForeground(Color.black);
        MaHoaDon1_lbl.setBackground(Color.white);

        MaHoaDon1_txt.setForeground(Color.black);
        MaHoaDon1_txt.setBackground(Color.white);
        MaHoaDon1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        KhachHang1_txt.setBackground(Color.white);
        KhachHang1_txt.setForeground(Color.black);
        KhachHang1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        KhachHang1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachHang1_txtActionPerformed(evt);
            }
        });

        KhachHang1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhachHang1_lbl.setText("Khách hàng:");
        KhachHang1_lbl.setForeground(Color.black);
        KhachHang1_lbl.setBackground(Color.white);


        SoDienThoai1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SoDienThoai1_lbl.setText("Số điện thoại:");
        SoDienThoai1_lbl.setBackground(Color.white);
        SoDienThoai1_lbl.setForeground(Color.black);

        SoDienThoai1_txt.setBackground(Color.white);
        SoDienThoai1_txt.setForeground(Color.black);
        SoDienThoai1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        SoDienThoai1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoDienThoai1_txtActionPerformed(evt);
            }
        });

        ThoiGianTao1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThoiGianTao1_lbl.setText("Thời gian tạo:");
        ThoiGianTao1_lbl.setBackground(Color.white);
        ThoiGianTao1_lbl.setForeground(Color.black);

        ThoiGianTao1_txt.setBackground(Color.white);
        ThoiGianTao1_txt.setForeground(Color.black);
        ThoiGianTao1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        ThoiGianThanhToan1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThoiGianThanhToan1_lbl.setText("Thời gian thanh toán:");
        ThoiGianThanhToan1_lbl.setBackground(Color.white);
        ThoiGianThanhToan1_lbl.setForeground(Color.black);

        ThoiGianThanhToan1_txt.setBackground(Color.white);
        ThoiGianThanhToan1_txt.setForeground(Color.black);
        ThoiGianThanhToan1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        LoaiThanhToan1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiThanhToan1_lbl.setText("Loại thanh toán:");
        LoaiThanhToan1_lbl.setBackground(Color.white);
        LoaiThanhToan1_lbl.setForeground(Color.black);

        LoaiThanhToan1_txt.setBackground(Color.white);
        LoaiThanhToan1_txt.setForeground(Color.black);
        LoaiThanhToan1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        GhiChu1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GhiChu1_lbl.setText("Ghi chú:");
        GhiChu1_lbl.setBackground(Color.white);
        GhiChu1_lbl.setForeground(Color.black);

        GhiChu1_txt.setBackground(Color.white);
        GhiChu1_txt.setForeground(Color.black);
        GhiChu1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        GhiChu1_txt.setColumns(20);
        GhiChu1_txt.setRows(5);
        scrollPaneGhiChu.setViewportView(GhiChu1_txt);
        scrollPaneGhiChu.setBackground(Color.white);

        javax.swing.GroupLayout ThongTin1Layout = new javax.swing.GroupLayout(ThongTin1);
        ThongTin1.setLayout(ThongTin1Layout);
        ThongTin1Layout.setHorizontalGroup(
                ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongTin1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneGhiChu)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin1Layout.createSequentialGroup()
                                                .addComponent(MaHoaDon1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addComponent(MaHoaDon1_txt))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin1Layout.createSequentialGroup()
                                                .addComponent(KhachHang1_lbl)
                                                .addGap(107, 107, 107)
                                                .addComponent(KhachHang1_txt))
                                        .addComponent(GhiChu1_lbl)
                                        .addGroup(ThongTin1Layout.createSequentialGroup()
                                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(ThoiGianTao1_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SoDienThoai1_lbl, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(97, 97, 97)
                                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ThoiGianTao1_txt)
                                                        .addComponent(SoDienThoai1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(ThongTin1Layout.createSequentialGroup()
                                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LoaiThanhToan1_lbl)
                                                        .addComponent(ThoiGianThanhToan1_lbl))
                                                .addGap(50, 50, 50)
                                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(LoaiThanhToan1_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                        .addComponent(ThoiGianThanhToan1_txt))))
                                .addContainerGap())
        );
        ThongTin1Layout.setVerticalGroup(
                ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongTin1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(ThongTin1Layout.createSequentialGroup()
                                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(MaHoaDon1_lbl)
                                                        .addComponent(MaHoaDon1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(KhachHang1_lbl)
                                                        .addComponent(KhachHang1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(SoDienThoai1_lbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(ThoiGianTao1_lbl))
                                        .addGroup(ThongTin1Layout.createSequentialGroup()
                                                .addComponent(SoDienThoai1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ThoiGianTao1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ThoiGianThanhToan1_lbl)
                                        .addComponent(ThoiGianThanhToan1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LoaiThanhToan1_lbl)
                                        .addComponent(LoaiThanhToan1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(GhiChu1_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TrangThai1.setBackground(new java.awt.Color(250, 238, 232));

        TrangThai1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThai1_lbl.setText("Trạng thái:");
        TrangThai1_lbl.setBackground(Color.white);
        TrangThai1_lbl.setForeground(Color.black);


        /**
         * Tiêu đề của JPanel Trạng thái
         */
        TrangThaiStatus1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TrangThaiStatus1_lbl.setText("Chờ xác nhận");
        TrangThaiStatus1_lbl.setBackground(Color.white);
        TrangThaiStatus1_lbl.setForeground(Color.black);



        TongTienSanPham1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TongTienSanPham1_lbl.setText("Tổng tiền sản phẩm:");
        TongTienSanPham1_lbl.setBackground(Color.white);
        TongTienSanPham1_lbl.setForeground(Color.black);

        TongTienSanPham1_txt.setBackground(Color.white);
        TongTienSanPham1_txt.setForeground(Color.black);
        TongTienSanPham1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        ChiTieuKhac1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChiTieuKhac1_lbl.setText("Chi tiêu khác:");
        ChiTieuKhac1_lbl.setBackground(Color.white);
        ChiTieuKhac1_lbl.setForeground(Color.black);

        ChiTietKhac1_txt.setBackground(Color.white);
        ChiTietKhac1_txt.setForeground(Color.black);
        ChiTietKhac1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        TongTienHoaDon1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TongTienHoaDon1_lbl.setText("Tổng tiền hóa đơn:");
        TongTienHoaDon1_lbl.setBackground(Color.white);
        TongTienHoaDon1_lbl.setForeground(Color.black);

        TongTienHoaDon1_txt.setBackground(Color.white);
        TongTienHoaDon1_txt.setForeground(Color.black);
        TongTienHoaDon1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        DiaChi1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DiaChi1_lbl.setText("Địa chỉ:");
        DiaChi1_lbl.setBackground(Color.white);
        DiaChi1_lbl.setForeground(Color.black);

        DiaChi1_txt.setColumns(20);
        DiaChi1_txt.setRows(5);
        DiaChi1_txt.setBackground(Color.white);
        DiaChi1_txt.setForeground(Color.black);
        DiaChi1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        scrollPaneDiaChi.setViewportView(DiaChi1_txt);
        scrollPaneDiaChi.setBackground(Color.white);

        javax.swing.GroupLayout TrangThai1Layout = new javax.swing.GroupLayout(TrangThai1);
        TrangThai1.setLayout(TrangThai1Layout);
        TrangThai1Layout.setHorizontalGroup(
                TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(TrangThai1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                                .addGap(47, 47, 47)
                                                                .addComponent(TrangThaiStatus1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(DiaChi1_lbl)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TongTienSanPham1_lbl)
                                                        .addComponent(ChiTieuKhac1_lbl)
                                                        .addComponent(TongTienHoaDon1_lbl))
                                                .addGap(39, 39, 39)
                                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TongTienSanPham1_txt)
                                                        .addComponent(ChiTietKhac1_txt)
                                                        .addComponent(TongTienHoaDon1_txt))))
                                .addContainerGap())
        );
        TrangThai1Layout.setVerticalGroup(
                TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TrangThai1_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(TrangThaiStatus1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TongTienSanPham1_lbl)
                                        .addComponent(TongTienSanPham1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ChiTieuKhac1_lbl)
                                        .addComponent(ChiTietKhac1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TongTienHoaDon1_lbl)
                                        .addComponent(TongTienHoaDon1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DiaChi1_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollPaneDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        XacNhan_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        XacNhan_Button.setText("Xác nhận hóa đơn");

        XacNhan_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhan_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HoaDonPhaCheLayout = new javax.swing.GroupLayout(HoaDonPhaChe);
        HoaDonPhaChe.setLayout(HoaDonPhaCheLayout);
        HoaDonPhaCheLayout.setHorizontalGroup(
                HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(HoaDon_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HoaDonChiTiet_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211))
                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(scrollPane_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(XacNhan_Button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addComponent(ThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane_HoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HoaDonPhaCheLayout.setVerticalGroup(
                HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HoaDon_lbl)
                                        .addComponent(HoaDonChiTiet_lbl))
                                .addGap(28, 28, 28)
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addComponent(jScrollPane_HoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ThongTin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 618, Short.MAX_VALUE))
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addComponent(scrollPane_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(XacNhan_Button)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabbedPane_HoaDon.addTab("Hóa đơn Pha chế", HoaDonPhaChe);

        LichSuHoaDon.setBackground(new java.awt.Color(250, 238, 232));

        MaHoaDon2_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaHoaDon2_lbl.setText("Mã hóa đơn:");
        MaHoaDon2_lbl.setBackground(Color.white);
        MaHoaDon2_lbl.setForeground(Color.black);

        MaHoaDon2_txt.setBackground(Color.white);
        MaHoaDon2_txt.setForeground(Color.black);
        MaHoaDon2_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        Tim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tim.setText("Tìm");

        TuNgay_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TuNgay_lbl.setText("Từ ngày:");
        TuNgay_lbl.setBackground(Color.white);
        TuNgay_lbl.setForeground(Color.black);


        DenNgay_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DenNgay_lbl.setText("Đến ngày:");
        DenNgay_lbl.setBackground(Color.white);
        DenNgay_lbl.setForeground(Color.black);



        TrangThai2_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThai2_lbl.setText("Trạng thái:");
        TrangThai2_lbl.setBackground(Color.white);
        TrangThai2_lbl.setForeground(Color.black);


        cbb_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chờ order", "Hoàn thành", " " }));
        cbb_TrangThai.setForeground(Color.black);
        cbb_TrangThai.setBackground(Color.white);

        Loc_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Loc_Button.setText("Lọc");

        HoaDonInfo_Table.setBackground(Color.white);
        HoaDonInfo_Table.setForeground(Color.black);
        HoaDonInfo_Table.setGridColor(Color.black);
        HoaDonInfo_Table.setShowGrid(true);

        HoaDonInfo_Table.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = HoaDonInfo_Table.getSelectedRow();
                String maHD = modelHoaDon.getValueAt(row, 0).toString();
                ArrayList<ChiTietHD> list = new ChiTietHD_DAO().getOrderDetail_ByID(maHD);

                modelChiTietHD.setRowCount(0);
                for(ChiTietHD cthd : list) {
                    modelChiTietHD.addRow(new Object[] {cthd.getSp().getTenSP(), cthd.getDonGia()
                            , cthd.getSoLuong(), cthd.getThanhTien(), null});
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
        HoaDonInfo_Table.setModel(modelHoaDon = new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Mã hóa đơn", "Người tạo", "Khách hàng", "Thời gian tạo", "Thời gian thanh toán", "Tổng tiền", "Địa chỉ", "Trạng thái"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        HoaDonInfo_Table.setShowHorizontalLines(true);
        HoaDonInfo_Table.setShowVerticalLines(true);
        HoaDonInfo_Table.setRowHeight(25);
        scrollPaneHoaDon_LichSuHD.setViewportView(HoaDonInfo_Table);
        scrollPaneHoaDon_LichSuHD.setBackground(Color.white);

        ChiTietHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChiTietHoaDon.setText("Chi tiết hóa đơn");
        ChiTietHoaDon.setBackground(Color.white);
        ChiTietHoaDon.setForeground(Color.black);

        jTableChiTietHD.setBackground(Color.white);
        jTableChiTietHD.setForeground(Color.black);
        jTableChiTietHD.setGridColor(Color.black);
        jTableChiTietHD.setShowGrid(true);
        jTableChiTietHD.setRowHeight(25);
        jTableChiTietHD.setModel(modelChiTietHD = new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", "Ghi chú"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneChiTietHoaDon.setViewportView(jTableChiTietHD);
        scrollPaneChiTietHoaDon.setBackground(Color.white);

        ThongTin2.setBackground(new java.awt.Color(250, 238, 232));

        lblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaHoaDon.setText("Mã hóa đơn:");
        lblMaHoaDon.setForeground(Color.black);
        lblMaHoaDon.setBackground(Color.white);

        txtMaHoaDon_LichSuHD.setForeground(Color.black);
        txtMaHoaDon_LichSuHD.setBackground(Color.white);
        txtMaHoaDon_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKhachHang.setText("Khách hàng:");
        lblKhachHang.setForeground(Color.black);
        lblKhachHang.setBackground(Color.white);

        txtKhachHang_LichSuHD.setForeground(Color.black);
        txtKhachHang_LichSuHD.setBackground(Color.white);
        txtKhachHang_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoDienThoai.setText("Số điện thoại:");
        lblSoDienThoai.setForeground(Color.black);
        lblSoDienThoai.setBackground(Color.white);

        txtSoDienThoai_LichSuHD.setForeground(Color.black);
        txtSoDienThoai_LichSuHD.setBackground(Color.white);
        txtSoDienThoai_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblThoiGianTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoiGianTao.setText("Thời gian tạo:");
        lblThoiGianTao.setForeground(Color.black);
        lblThoiGianTao.setBackground(Color.white);

        txtThoiGianTao_LichSuHD.setForeground(Color.black);
        txtThoiGianTao_LichSuHD.setBackground(Color.white);
        txtThoiGianTao_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblThoiGianThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoiGianThanhToan.setText("Thời gian thanh toán:");
        lblThoiGianThanhToan.setForeground(Color.black);
        lblThoiGianThanhToan.setBackground(Color.white);

        //TODO: thiếu txt thời gian thanh toán
//        thoi.setForeground(Color.black);
//        txtThoiGianTao_LichSuHD.setBackground(Color.white);
//        txtThoiGianTao_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblLoaiThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoaiThanhToan.setText("Loại thanh toán:");
        lblLoaiThanhToan.setForeground(Color.black);
        lblLoaiThanhToan.setBackground(Color.white);

        txtLoaiThanhToan_LichSuHD.setForeground(Color.black);
        txtLoaiThanhToan_LichSuHD.setBackground(Color.white);
        txtLoaiThanhToan_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGhiChu.setText("Ghi chú:");
        lblGhiChu.setForeground(Color.black);
        lblGhiChu.setBackground(Color.white);


        textArea_GhiChu.setColumns(20);
        textArea_GhiChu.setRows(5);
        textArea_GhiChu.setForeground(Color.black);
        textArea_GhiChu.setBackground(Color.white);
        textArea_GhiChu.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        scrollPaneGhiChu_LichSuHD.setViewportView(textArea_GhiChu);

        javax.swing.GroupLayout ThongTin2Layout = new javax.swing.GroupLayout(ThongTin2);
        ThongTin2.setLayout(ThongTin2Layout);
        ThongTin2Layout.setHorizontalGroup(
                ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneGhiChu_LichSuHD)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin2Layout.createSequentialGroup()
                                                .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addComponent(txtMaHoaDon_LichSuHD))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin2Layout.createSequentialGroup()
                                                .addComponent(lblKhachHang)
                                                .addGap(107, 107, 107)
                                                .addComponent(txtKhachHang_LichSuHD))
                                        .addComponent(lblThoiGianThanhToan)
                                        .addComponent(lblGhiChu)
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lblThoiGianTao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(97, 97, 97)
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtThoiGianTao_LichSuHD)
                                                        .addComponent(txtSoDienThoai_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addComponent(lblLoaiThanhToan)
                                                .addGap(82, 82, 82)
                                                .addComponent(txtLoaiThanhToan_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        ThongTin2Layout.setVerticalGroup(
                ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblMaHoaDon)
                                                        .addComponent(txtMaHoaDon_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblKhachHang)
                                                        .addComponent(txtKhachHang_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblSoDienThoai)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblThoiGianTao))
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addComponent(txtSoDienThoai_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtThoiGianTao_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblThoiGianThanhToan)
                                .addGap(18, 18, 18)
                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblLoaiThanhToan)
                                        .addComponent(txtLoaiThanhToan_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblGhiChu)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneGhiChu_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TrangThai2.setBackground(new java.awt.Color(250, 238, 232));

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái:");
        lblTrangThai.setBackground(Color.white);
        lblTrangThai.setForeground(Color.black);

        lblTrangThai_Status.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTrangThai_Status.setText("Hoàn thành");
        lblTrangThai_Status.setForeground(Color.black);

        lblTongTienSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienSanPham.setText("Tổng tiền sản phẩm:");
        lblTongTienSanPham.setBackground(Color.white);
        lblTongTienSanPham.setForeground(Color.black);

        txt_TongTienSP.setForeground(Color.black);
        txt_TongTienSP.setBackground(Color.white);
        txt_TongTienSP.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        lblChiTieuKhac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiTieuKhac.setText("Chi tiêu khác:");
        lblChiTieuKhac.setBackground(Color.white);
        lblChiTieuKhac.setForeground(Color.black);

        txt_ChiTietKhac.setForeground(Color.black);
        txt_ChiTietKhac.setBackground(Color.white);
        txt_ChiTietKhac.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblTongTienHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienHoaDon.setText("Tổng tiền hóa đơn:");
        lblTongTienHoaDon.setBackground(Color.white);
        lblTongTienHoaDon.setForeground(Color.black);


        txt_TongTienHD.setForeground(Color.black);
        txt_TongTienHD.setBackground(Color.white);
        txt_TongTienHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");
        lblDiaChi.setBackground(Color.white);
        lblDiaChi.setForeground(Color.black);

        textArea_DiaChi.setColumns(20);
        textArea_DiaChi.setRows(5);
        textArea_DiaChi.setForeground(Color.black);
        textArea_DiaChi.setBackground(Color.white);
        textArea_DiaChi.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        scrollPaneDiaChi_LichSuHD.setViewportView(textArea_DiaChi);

        javax.swing.GroupLayout TrangThai2Layout = new javax.swing.GroupLayout(TrangThai2);
        TrangThai2.setLayout(TrangThai2Layout);
        TrangThai2Layout.setHorizontalGroup(
                TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TrangThai2Layout.createSequentialGroup()
                                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TrangThai2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTongTienSanPham)
                                                        .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblChiTieuKhac)
                                                        .addComponent(lblTongTienHoaDon)
                                                        .addComponent(lblDiaChi))
                                                .addGap(42, 42, 42)
                                                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_TongTienSP)
                                                        .addComponent(txt_ChiTietKhac)
                                                        .addComponent(txt_TongTienHD)))
                                        .addComponent(scrollPaneDiaChi_LichSuHD, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(TrangThai2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTrangThai_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrangThai2Layout.setVerticalGroup(
                TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TrangThai2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTrangThai)
                                .addGap(12, 12, 12)
                                .addComponent(lblTrangThai_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTongTienSanPham)
                                        .addComponent(txt_TongTienSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblChiTieuKhac)
                                        .addComponent(txt_TongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTongTienHoaDon)
                                        .addComponent(txt_ChiTietKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDiaChi)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneDiaChi_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton15.setText("Khôi phục hóa đơn");

        javax.swing.GroupLayout LichSuHoaDonLayout = new javax.swing.GroupLayout(LichSuHoaDon);
        LichSuHoaDon.setLayout(LichSuHoaDonLayout);
        LichSuHoaDonLayout.setHorizontalGroup(
                LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(scrollPaneHoaDon_LichSuHD)
                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(MaHoaDon2_lbl)
                                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                                .addComponent(MaHoaDon2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(TuNgay_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(151, 151, 151)
                                                .addComponent(DenNgay_lbl)
                                                .addGap(141, 141, 141)
                                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(TrangThai2_lbl))
                                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cbb_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Loc_Button))))
                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                .addComponent(ThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(scrollPaneChiTietHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LichSuHoaDonLayout.createSequentialGroup()
                                                                .addComponent(jButton15)
                                                                .addGap(144, 144, 144))))
                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                .addGap(535, 535, 535)
                                                .addComponent(ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LichSuHoaDonLayout.setVerticalGroup(
                LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MaHoaDon2_lbl)
                                        .addComponent(TuNgay_lbl)
                                        .addComponent(DenNgay_lbl)
                                        .addComponent(TrangThai2_lbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                .addComponent(MaHoaDon2_txt)
                                                .addGap(2, 2, 2))
                                        .addComponent(Loc_Button)
                                        .addComponent(cbb_TrangThai))
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneHoaDon_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChiTietHoaDon)
                                .addGap(18, 18, 18)
                                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ThongTin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TrangThai2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                        .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                                .addComponent(scrollPaneChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(491, Short.MAX_VALUE))
        );

        tabbedPane_HoaDon.addTab("Lịch sử hóa đơn", LichSuHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1278, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(tabbedPane_HoaDon)
                                        .addContainerGap()))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1291, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(tabbedPane_HoaDon)
                                        .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XacNhan_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XacNhan_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XacNhan_ButtonActionPerformed

    private void KhachHang1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachHang1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KhachHang1_txtActionPerformed

    private void SoDienThoai1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoDienThoai1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoDienThoai1_txtActionPerformed

    private void loadData(ArrayList<entity.HoaDon> list){
        modelHoaDon.setRowCount(0);
        for(entity.HoaDon hd : list) {
            modelHoaDon.addRow(new Object[] {hd.getMaHD(), hd.getNhanVien().getMaNV() , hd.getKhachHang().getMaKH()
                    , hd.getNgayLapHD(), hd.getGioRa(), hd.getTongTien(), null, null});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChiTietHoaDon;
    private javax.swing.JTextField ChiTietKhac1_txt;
    private javax.swing.JLabel ChiTieuKhac1_lbl;
    private javax.swing.JLabel DenNgay_lbl;
    private javax.swing.JLabel DiaChi1_lbl;
    private javax.swing.JTextArea DiaChi1_txt;
    private javax.swing.JLabel GhiChu1_lbl;
    private javax.swing.JTextArea GhiChu1_txt;
    private javax.swing.JScrollPane scrollPane_HoaDon;
    private javax.swing.JScrollPane jScrollPane_HoaDonChiTiet;
    private javax.swing.JTable HoaDonChiTiet_Table;
    private javax.swing.JLabel HoaDonChiTiet_lbl;
    private javax.swing.JTable HoaDonInfo_Table;
    private javax.swing.JPanel HoaDonPhaChe;
    private javax.swing.JTable HoaDon_Table;
    private javax.swing.JLabel HoaDon_lbl;
    private javax.swing.JLabel KhachHang1_lbl;
    private javax.swing.JTextField KhachHang1_txt;
    private javax.swing.JPanel LichSuHoaDon;
    private javax.swing.JLabel LoaiThanhToan1_lbl;
    private javax.swing.JTextField LoaiThanhToan1_txt;
    private javax.swing.JButton Loc_Button;
    private javax.swing.JLabel MaHoaDon1_lbl;
    private javax.swing.JTextField MaHoaDon1_txt;
    private javax.swing.JLabel MaHoaDon2_lbl;
    private javax.swing.JTextField MaHoaDon2_txt;
    private javax.swing.JLabel SoDienThoai1_lbl;
    private javax.swing.JTextField SoDienThoai1_txt;
    private javax.swing.JLabel ThoiGianTao1_lbl;
    private javax.swing.JTextField ThoiGianTao1_txt;
    private javax.swing.JLabel ThoiGianThanhToan1_lbl;
    private javax.swing.JTextField ThoiGianThanhToan1_txt;
    private javax.swing.JPanel ThongTin1;
    private javax.swing.JPanel ThongTin2;
    private javax.swing.JButton Tim;
    private javax.swing.JLabel TongTienHoaDon1_lbl;
    private javax.swing.JTextField TongTienHoaDon1_txt;
    private javax.swing.JLabel TongTienSanPham1_lbl;
    private javax.swing.JTextField TongTienSanPham1_txt;
    private javax.swing.JPanel TrangThai1;
    private javax.swing.JLabel TrangThai1_lbl;
    private javax.swing.JPanel TrangThai2;
    private javax.swing.JLabel TrangThai2_lbl;
    private javax.swing.JLabel TrangThaiStatus1_lbl;
    private javax.swing.JLabel TuNgay_lbl;
    private javax.swing.JButton XacNhan_Button;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> cbb_TrangThai;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblThoiGianTao;
    private javax.swing.JLabel lblThoiGianThanhToan;
    private javax.swing.JLabel lblLoaiThanhToan;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThai_Status;
    private javax.swing.JLabel lblTongTienSanPham;
    private javax.swing.JLabel lblChiTieuKhac;
    private javax.swing.JLabel lblTongTienHoaDon;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JScrollPane scrollPaneGhiChu;
    private javax.swing.JScrollPane scrollPaneDiaChi;
    private javax.swing.JScrollPane scrollPaneHoaDon_LichSuHD;
    private javax.swing.JScrollPane scrollPaneChiTietHoaDon;
    private javax.swing.JScrollPane scrollPaneGhiChu_LichSuHD;
    private javax.swing.JScrollPane scrollPaneDiaChi_LichSuHD;
    private javax.swing.JTabbedPane tabbedPane_HoaDon;
    private javax.swing.JTable jTableChiTietHD;
    private javax.swing.JTextArea textArea_GhiChu;
    private javax.swing.JTextArea textArea_DiaChi;
    private javax.swing.JTextField txt_TongTienSP;
    private javax.swing.JTextField txtSoDienThoai_LichSuHD;
    private javax.swing.JTextField txtLoaiThanhToan_LichSuHD;
    private javax.swing.JTextField txt_TongTienHD;
    private javax.swing.JTextField txt_ChiTietKhac;
    private javax.swing.JTextField txtMaHoaDon_LichSuHD;
    private javax.swing.JTextField txtKhachHang_LichSuHD;
    private javax.swing.JTextField txtThoiGianTao_LichSuHD;
    // End of variables declaration//GEN-END:variables
}