/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import connect.ConnectDB;
import dao.ChiTietHD_DAO;
import entity.ChiTietHD;
import entity.SanPham;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class HoaDon extends javax.swing.JPanel {

    private ChiTietHD_DAO chiTietHD_dao;
    private DefaultTableModel modelHoaDon;
    private DefaultTableModel modelChiTietHD;

    /**
     * Creates new form HoaDon
     */
    public HoaDon() {
        ConnectDB.getInstance().connect();
        initComponents();
        chiTietHD_dao = new ChiTietHD_DAO();

        ArrayList<ChiTietHD> cthd = chiTietHD_dao.getAllOrder();
        loadData(cthd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        HoaDonPhaChe = new javax.swing.JPanel();
        HoaDon_lbl = new javax.swing.JLabel();
        HoaDon = new javax.swing.JScrollPane();
        HoaDon_Table = new javax.swing.JTable();
        HoaDonChiTiet_lbl = new javax.swing.JLabel();
        HoaDonChiTiet = new javax.swing.JScrollPane();
        HoaDonChiTiet_Table = new javax.swing.JTable();
        ThongTin1 = new javax.swing.JPanel();
        MaHoaDon1_lbl = new javax.swing.JLabel();
        MaHoaDon1_txt = new javax.swing.JTextField();
        KhachHang1_txt = new javax.swing.JTextField();
        KhachHang1_lbl = new javax.swing.JLabel();
        SoDienThoai1_lbl = new javax.swing.JLabel();
        ThoiGianTao1_txt = new javax.swing.JTextField();
        SoDienThoai1_txt = new javax.swing.JTextField();
        ThoiGianTao1_lbl = new javax.swing.JLabel();
        ThoiGianThanhToan1_lbl = new javax.swing.JLabel();
        LoaiThanhToan1_lbl = new javax.swing.JLabel();
        LoaiThanhToan1_txt = new javax.swing.JTextField();
        GhiChu1_lbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GhiChu1_txt = new javax.swing.JTextArea();
        ThoiGianThanhToan1_txt = new javax.swing.JTextField();
        TrangThai1 = new javax.swing.JPanel();
        TrangThai1_lbl = new javax.swing.JLabel();
        TrangThaiStatus1_lbl = new javax.swing.JLabel();
        TongTienSanPham1_lbl = new javax.swing.JLabel();
        ChiTieuKhac1_lbl = new javax.swing.JLabel();
        TongTienHoaDon1_lbl = new javax.swing.JLabel();
        DiaChi1_lbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DiaChi1_txt = new javax.swing.JTextArea();
        TongTienSanPham1_txt = new javax.swing.JTextField();
        ChiTietKhac1_txt = new javax.swing.JTextField();
        TongTienHoaDon1_txt = new javax.swing.JTextField();
        XacNhan_Button = new javax.swing.JButton();
        LichSuHoaDon = new javax.swing.JPanel();
        MaHoaDon2_lbl = new javax.swing.JLabel();
        MaHoaDon2_txt = new javax.swing.JTextField();
        Tim = new javax.swing.JButton();
        TuNgay_lbl = new javax.swing.JLabel();
        DenNgay_lbl = new javax.swing.JLabel();
        TrangThai2_lbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Loc_Button = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        HoaDonInfo_Table = new javax.swing.JTable();
        ChiTietHoaDon = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableChiTietHD = new javax.swing.JTable();
        ThongTin2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        TrangThai2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 238, 232));

        HoaDonPhaChe.setBackground(new java.awt.Color(250, 238, 232));

        HoaDon_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HoaDon_lbl.setText("Hóa đơn");

        HoaDon_Table.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người tạo", "Thời gian tạo", "Tổng tiền", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, Double.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        HoaDon.setViewportView(HoaDon_Table);

        HoaDonChiTiet_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HoaDonChiTiet_lbl.setText("Hóa đơn chi tiết");

        HoaDonChiTiet_Table.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        HoaDonChiTiet_Table.setShowVerticalLines(true);
        HoaDonChiTiet.setViewportView(HoaDonChiTiet_Table);

        ThongTin1.setBackground(new java.awt.Color(250, 238, 232));

        MaHoaDon1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaHoaDon1_lbl.setText("Mã hóa đơn:");

        KhachHang1_txt.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                KhachHang1_txtActionPerformed(evt);
            }
        });

        KhachHang1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KhachHang1_lbl.setText("Khách hàng:");

        SoDienThoai1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SoDienThoai1_lbl.setText("Số điện thoại:");

        SoDienThoai1_txt.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SoDienThoai1_txtActionPerformed(evt);
            }
        });

        ThoiGianTao1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThoiGianTao1_lbl.setText("Thời gian tạo:");

        ThoiGianThanhToan1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThoiGianThanhToan1_lbl.setText("Thời gian thanh toán:");

        LoaiThanhToan1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiThanhToan1_lbl.setText("Loại thanh toán:");

        GhiChu1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GhiChu1_lbl.setText("Ghi chú:");

        GhiChu1_txt.setColumns(20);
        GhiChu1_txt.setRows(5);
        jScrollPane3.setViewportView(GhiChu1_txt);

        javax.swing.GroupLayout ThongTin1Layout = new javax.swing.GroupLayout(ThongTin1);
        ThongTin1.setLayout(ThongTin1Layout);
        ThongTin1Layout.setHorizontalGroup(
            ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin1Layout.createSequentialGroup()
                        .addComponent(MaHoaDon1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(MaHoaDon1_txt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin1Layout.createSequentialGroup()
                        .addComponent(KhachHang1_lbl)
                        .addGap(107, 107, 107)
                        .addComponent(KhachHang1_txt))
                    .addComponent(GhiChu1_lbl)
                    .addGroup(ThongTin1Layout.createSequentialGroup()
                        .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ThoiGianTao1_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SoDienThoai1_lbl, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(97, 97, 97)
                        .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ThoiGianTao1_txt)
                            .addComponent(SoDienThoai1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTin1Layout.createSequentialGroup()
                        .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoaiThanhToan1_lbl)
                            .addComponent(ThoiGianThanhToan1_lbl))
                        .addGap(50, 50, 50)
                        .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoaiThanhToan1_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(ThoiGianThanhToan1_txt))))
                .addContainerGap())
        );
        ThongTin1Layout.setVerticalGroup(
            ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTin1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThongTin1Layout.createSequentialGroup()
                        .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaHoaDon1_lbl)
                            .addComponent(MaHoaDon1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KhachHang1_lbl)
                            .addComponent(KhachHang1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(SoDienThoai1_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(ThoiGianTao1_lbl))
                    .addGroup(ThongTin1Layout.createSequentialGroup()
                        .addComponent(SoDienThoai1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ThoiGianTao1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThoiGianThanhToan1_lbl)
                    .addComponent(ThoiGianThanhToan1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoaiThanhToan1_lbl)
                    .addComponent(LoaiThanhToan1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GhiChu1_lbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TrangThai1.setBackground(new java.awt.Color(250, 238, 232));

        TrangThai1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThai1_lbl.setText("Trạng thái:");

        TrangThaiStatus1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TrangThaiStatus1_lbl.setText("Chờ xác nhận");

        TongTienSanPham1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TongTienSanPham1_lbl.setText("Tổng tiền sản phẩm:");

        ChiTieuKhac1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChiTieuKhac1_lbl.setText("Chi tiêu khác:");

        TongTienHoaDon1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TongTienHoaDon1_lbl.setText("Tổng tiền hóa đơn:");

        DiaChi1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DiaChi1_lbl.setText("Địa chỉ:");

        DiaChi1_txt.setColumns(20);
        DiaChi1_txt.setRows(5);
        jScrollPane4.setViewportView(DiaChi1_txt);

        javax.swing.GroupLayout TrangThai1Layout = new javax.swing.GroupLayout(TrangThai1);
        TrangThai1.setLayout(TrangThai1Layout);
        TrangThai1Layout.setHorizontalGroup(
            TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangThai1Layout.createSequentialGroup()
                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(TrangThai1Layout.createSequentialGroup()
                        .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TrangThai1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(TrangThaiStatus1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DiaChi1_lbl)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TrangThai1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TongTienSanPham1_lbl)
                            .addComponent(ChiTieuKhac1_lbl)
                            .addComponent(TongTienHoaDon1_lbl))
                        .addGap(39, 39, 39)
                        .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TongTienSanPham1_txt)
                            .addComponent(ChiTietKhac1_txt)
                            .addComponent(TongTienHoaDon1_txt))))
                .addContainerGap())
        );
        TrangThai1Layout.setVerticalGroup(
            TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangThai1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrangThai1_lbl)
                .addGap(18, 18, 18)
                .addComponent(TrangThaiStatus1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TongTienSanPham1_lbl)
                    .addComponent(TongTienSanPham1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChiTieuKhac1_lbl)
                    .addComponent(ChiTietKhac1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TongTienHoaDon1_lbl)
                    .addComponent(TongTienHoaDon1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DiaChi1_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        XacNhan_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        XacNhan_Button.setText("Xác nhận hóa đơn");
        XacNhan_Button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                XacNhan_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HoaDonPhaCheLayout = new javax.swing.GroupLayout(HoaDonPhaChe);
        HoaDonPhaChe.setLayout(HoaDonPhaCheLayout);
        HoaDonPhaCheLayout.setHorizontalGroup(
            HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(HoaDon_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HoaDonChiTiet_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(XacNhan_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                        .addComponent(ThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(HoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HoaDonPhaCheLayout.setVerticalGroup(
            HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoaDon_lbl)
                    .addComponent(HoaDonChiTiet_lbl))
                .addGap(28, 28, 28)
                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                        .addComponent(HoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ThongTin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 618, Short.MAX_VALUE))
                    .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                        .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(XacNhan_Button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Hóa đơn Pha chế", HoaDonPhaChe);

        LichSuHoaDon.setBackground(new java.awt.Color(250, 238, 232));

        MaHoaDon2_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaHoaDon2_lbl.setText("Mã hóa đơn:");

        Tim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tim.setText("Tìm");

        TuNgay_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TuNgay_lbl.setText("Từ ngày:");

        DenNgay_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DenNgay_lbl.setText("Đến ngày:");

        TrangThai2_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThai2_lbl.setText("Trạng thái:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chờ order", "Hoàn thành", " " }));

        Loc_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Loc_Button.setText("Lọc");

        HoaDonInfo_Table.setModel(modelHoaDon = new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người tạo", "Khách hàng", "Thời gian tạo", "Thời gian thanh toán", "Tổng tiền", "Địa chỉ", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, Float.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        HoaDonInfo_Table.setShowHorizontalLines(true);
        HoaDonInfo_Table.setShowVerticalLines(true);
        jScrollPane5.setViewportView(HoaDonInfo_Table);

        ChiTietHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChiTietHoaDon.setText("Chi tiết hóa đơn");

        jTableChiTietHD.setModel(modelChiTietHD = new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                String.class, Integer.class, Double.class, Double.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableChiTietHD);

        ThongTin2.setBackground(new java.awt.Color(250, 238, 232));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Mã hóa đơn:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Khách hàng:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Số điện thoại:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Thời gian tạo:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Thời gian thanh toán:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Loại thanh toán:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Ghi chú:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane7.setViewportView(jTextArea3);

        javax.swing.GroupLayout ThongTin2Layout = new javax.swing.GroupLayout(ThongTin2);
        ThongTin2.setLayout(ThongTin2Layout);
        ThongTin2Layout.setHorizontalGroup(
            ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jTextField7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(107, 107, 107)
                        .addComponent(jTextField8))
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addGroup(ThongTin2Layout.createSequentialGroup()
                        .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(97, 97, 97)
                        .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTin2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(82, 82, 82)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ThongTin2Layout.setVerticalGroup(
            ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThongTin2Layout.createSequentialGroup()
                        .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25))
                    .addGroup(ThongTin2Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TrangThai2.setBackground(new java.awt.Color(250, 238, 232));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Trạng thái:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("Hoàn thành");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Tổng tiền sản phẩm:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Chi tiêu khác:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Tổng tiền hóa đơn:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Địa chỉ:");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane8.setViewportView(jTextArea4);

        javax.swing.GroupLayout TrangThai2Layout = new javax.swing.GroupLayout(TrangThai2);
        TrangThai2.setLayout(TrangThai2Layout);
        TrangThai2Layout.setHorizontalGroup(
            TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangThai2Layout.createSequentialGroup()
                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrangThai2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addGap(42, 42, 42)
                        .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(TrangThai2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrangThai2Layout.setVerticalGroup(
            TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangThai2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(12, 12, 12)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton15.setText("Khôi phục hóa đơn");

        javax.swing.GroupLayout LichSuHoaDonLayout = new javax.swing.GroupLayout(LichSuHoaDon);
        LichSuHoaDon.setLayout(LichSuHoaDonLayout);
        LichSuHoaDonLayout.setHorizontalGroup(
            LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                        .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaHoaDon2_lbl)
                            .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                .addComponent(MaHoaDon2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(TuNgay_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(DenNgay_lbl)
                        .addGap(141, 141, 141)
                        .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(TrangThai2_lbl))
                            .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Loc_Button))))
                    .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                        .addComponent(ThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LichSuHoaDonLayout.createSequentialGroup()
                                .addComponent(jButton15)
                                .addGap(144, 144, 144))))
                    .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                        .addGap(535, 535, 535)
                        .addComponent(ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LichSuHoaDonLayout.setVerticalGroup(
            LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaHoaDon2_lbl)
                    .addComponent(TuNgay_lbl)
                    .addComponent(DenNgay_lbl)
                    .addComponent(TrangThai2_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                        .addComponent(MaHoaDon2_txt)
                        .addGap(2, 2, 2))
                    .addComponent(Loc_Button)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChiTietHoaDon)
                .addGap(18, 18, 18)
                .addGroup(LichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ThongTin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrangThai2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(LichSuHoaDonLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lịch sử hóa đơn", LichSuHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1278, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1291, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XacNhan_ButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_XacNhan_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XacNhan_ButtonActionPerformed

    private void KhachHang1_txtActionPerformed(ActionEvent evt) {//GEN-FIRST:event_KhachHang1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KhachHang1_txtActionPerformed

    private void SoDienThoai1_txtActionPerformed(ActionEvent evt) {//GEN-FIRST:event_SoDienThoai1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoDienThoai1_txtActionPerformed

    private void loadData(ArrayList<ChiTietHD> list){
        modelHoaDon.setRowCount(0);
        modelChiTietHD.setRowCount(0);
        for(ChiTietHD cthd : list) {
            modelHoaDon.addRow(new Object[] {cthd.getHd().getMaHD(), cthd.getHd().getNhanVien().getTenNV(), cthd.getHd().getKhachHang().getTenKH()
                    , cthd.getHd().getNgayLapHD(), cthd.getHd().getGioRa(), null, cthd.getHd().getTongTien(), null, null});
            modelChiTietHD.addRow(new Object[] {cthd.getSp().getTenSP(), cthd.getSp().getDonGia(), cthd.getSoLuong(), cthd.getThanhTien(), null});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChiTietHoaDon;
    private javax.swing.JTextField ChiTietKhac1_txt;
    private javax.swing.JLabel ChiTieuKhac1_lbl;
    private javax.swing.JLabel DenNgay_lbl;
    private javax.swing.JLabel DiaChi1_lbl;
    private javax.swing.JTextArea DiaChi1_txt;
    private javax.swing.JLabel GhiChu1_lbl;
    private javax.swing.JTextArea GhiChu1_txt;
    private javax.swing.JScrollPane HoaDon;
    private javax.swing.JScrollPane HoaDonChiTiet;
    private javax.swing.JTable HoaDonChiTiet_Table;
    private javax.swing.JLabel HoaDonChiTiet_lbl;
    private javax.swing.JTable HoaDonInfo_Table;
    private javax.swing.JPanel HoaDonPhaChe;
    private javax.swing.JTable HoaDon_Table;
    private javax.swing.JLabel HoaDon_lbl;
    private javax.swing.JLabel KhachHang1_lbl;
    private javax.swing.JTextField KhachHang1_txt;
    private javax.swing.JPanel LichSuHoaDon;
    private javax.swing.JLabel LoaiThanhToan1_lbl;
    private javax.swing.JTextField LoaiThanhToan1_txt;
    private javax.swing.JButton Loc_Button;
    private javax.swing.JLabel MaHoaDon1_lbl;
    private javax.swing.JTextField MaHoaDon1_txt;
    private javax.swing.JLabel MaHoaDon2_lbl;
    private javax.swing.JTextField MaHoaDon2_txt;
    private javax.swing.JLabel SoDienThoai1_lbl;
    private javax.swing.JTextField SoDienThoai1_txt;
    private javax.swing.JLabel ThoiGianTao1_lbl;
    private javax.swing.JTextField ThoiGianTao1_txt;
    private javax.swing.JLabel ThoiGianThanhToan1_lbl;
    private javax.swing.JTextField ThoiGianThanhToan1_txt;
    private javax.swing.JPanel ThongTin1;
    private javax.swing.JPanel ThongTin2;
    private javax.swing.JButton Tim;
    private javax.swing.JLabel TongTienHoaDon1_lbl;
    private javax.swing.JTextField TongTienHoaDon1_txt;
    private javax.swing.JLabel TongTienSanPham1_lbl;
    private javax.swing.JTextField TongTienSanPham1_txt;
    private javax.swing.JPanel TrangThai1;
    private javax.swing.JLabel TrangThai1_lbl;
    private javax.swing.JPanel TrangThai2;
    private javax.swing.JLabel TrangThai2_lbl;
    private javax.swing.JLabel TrangThaiStatus1_lbl;
    private javax.swing.JLabel TuNgay_lbl;
    private javax.swing.JButton XacNhan_Button;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableChiTietHD;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
