/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 * @author Admin
 */
public class HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form HoaDon
     */
    public HoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tabHoaDon = new javax.swing.JTabbedPane();
        panelHoaDon = new javax.swing.JPanel();
        lblHoaDon_HDPC = new javax.swing.JLabel();
        scrollPaneHoaDon = new javax.swing.JScrollPane();
        tableHoaDon_HDPC = new javax.swing.JTable();
        lblHoaDonChiTiet_HDPC = new javax.swing.JLabel();
        scrollPaneHoaDonChiTiet = new javax.swing.JScrollPane();
        tableHoaDonChiTiet_HDPC = new javax.swing.JTable();
        panelThongTin_HDPC = new javax.swing.JPanel();
        lblMaHoaDon_HDPC = new javax.swing.JLabel();
        txtMaHoaDon_HDPC = new javax.swing.JTextField();
        txtKhachHang_HDPC = new javax.swing.JTextField();
        lblKhachHang_HDPC = new javax.swing.JLabel();
        lblSoDienThoai_HDPC = new javax.swing.JLabel();
        txtThoIGianTao_HDPC = new javax.swing.JTextField();
        txtSoDienThoai_HDPC = new javax.swing.JTextField();
        lblThoiGianTao_HDPC = new javax.swing.JLabel();
        lblThoiGianThanhToan_HDPC = new javax.swing.JLabel();
        lblLoaiThanhToan_HDPC = new javax.swing.JLabel();
        txtLoaiThanhToan_HDPC = new javax.swing.JTextField();
        lblGhiChu_HDPC = new javax.swing.JLabel();
        scrollPaneGhiChu_HDPC = new javax.swing.JScrollPane();
        txtGhiChu_HDPC = new javax.swing.JTextArea();
        txtThoiGianThanhToan_HDPC = new javax.swing.JTextField();
        panelTrangThai_HDPC = new javax.swing.JPanel();
        labelTrangThai_HDPC = new javax.swing.JLabel();
        lblTrangThai_Status_HDPC = new javax.swing.JLabel();
        lblTongTienSanPham_HDPC = new javax.swing.JLabel();
        lblChiTieuKhac_HDPC = new javax.swing.JLabel();
        lblTongTienHoaDon = new javax.swing.JLabel();
        txtTongTienSanPham_HDPC = new javax.swing.JTextField();
        txtChiTieuKhac_HDPC = new javax.swing.JTextField();
        txtTongTienHoaDon_HDPC = new javax.swing.JTextField();
        btnXacNhanHoaDon_HDPC = new javax.swing.JButton();
        panelLichSuHoaDon = new javax.swing.JPanel();
        lblMaHoaDonCanTim_LSHD = new javax.swing.JLabel();
        txtMaHoaDonCanTim_LSHD = new javax.swing.JTextField();
        btnTimMaHoaDon_LSHD = new javax.swing.JButton();
        lblTuNgay_LSHD = new javax.swing.JLabel();
        lblDenNgay_LSHD = new javax.swing.JLabel();
        lblTrangThai_LSHD = new javax.swing.JLabel();
        comboBoxTrangThai_LSHD = new javax.swing.JComboBox<>();
        btnLoc_LSHD = new javax.swing.JButton();
        scrollPaneHoaDonCanTim_LSHD = new javax.swing.JScrollPane();
        tableHoaDonCanTim_LSHD = new javax.swing.JTable();
        lblChiTietHoaDon_LSHD = new javax.swing.JLabel();
        scrollPaneHonDon = new javax.swing.JScrollPane();
        tableHoaDon = new javax.swing.JTable();
        panelThongTin_LSHD = new javax.swing.JPanel();
        lblMaHoaDon_LSHD = new javax.swing.JLabel();
        txtMaHoaDon_LSHD = new javax.swing.JTextField();
        txtKhachHang_LSHD = new javax.swing.JTextField();
        lblKhachHang_LSHD = new javax.swing.JLabel();
        lblSoDienThoai_LSHD = new javax.swing.JLabel();
        txtThoiGianTao_LSHD = new javax.swing.JTextField();
        txtSoDienThoai_LSHD = new javax.swing.JTextField();
        lblThoiGianTao = new javax.swing.JLabel();
        lblThoiGianThanhToan_LSHD = new javax.swing.JLabel();
        lblLoaiThanhToan = new javax.swing.JLabel();
        txtLoaiThanhToan = new javax.swing.JTextField();
        lblGhiChu_LSHD = new javax.swing.JLabel();
        scrollPaneGhiChu = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        txtThoiGianThanhToan_LSHD = new javax.swing.JTextField();
        panelTrangThai_LSHD = new javax.swing.JPanel();
        lblTrangthai_LSHD = new javax.swing.JLabel();
        lblTrangThai_Status_LSHD = new javax.swing.JLabel();
        lblTongTienSanPham_LSHD = new javax.swing.JLabel();
        lblChiTieuKhac_LSHD = new javax.swing.JLabel();
        lblTongTIenHoaDon_LSHD = new javax.swing.JLabel();
        txtTongTienSanPham_LSHD = new javax.swing.JTextField();
        txtChiTieuKhac_LSHD = new javax.swing.JTextField();
        txtTongTienHoaDon_LSHD = new javax.swing.JTextField();
        btnKhoiPhucHoaDon_LSHD = new javax.swing.JButton();
        chooserTuNgay_LSHD = new com.toedter.calendar.JDateChooser();
        chooserDenNgay_LSHD = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(250, 238, 232));

        panelHoaDon.setBackground(new java.awt.Color(250, 238, 232));

        lblHoaDon_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHoaDon_HDPC.setText("Hóa đơn");

<<<<<<< HEAD
        tableHoaDon_HDPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người tạo", "Thời gian tạo", "Tổng tiền", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
=======
        HoaDon_Table.setRowHeight(25);
        HoaDon_Table.setForeground(Color.black);
        HoaDon_Table.setBackground(Color.WHITE);
        HoaDon_Table.setShowGrid(true);
        HoaDon_Table.setGridColor(Color.black);
        HoaDon_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String[]{
                        "Mã hóa đơn", "Người tạo", "Thời gian tạo", "Tổng tiền", "Trạng thái"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
>>>>>>> 9daff001e75a0a3cb54faaf95e1ffa5cd4df89e1
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tableHoaDon_HDPC.setShowGrid(true);
        tableHoaDon_HDPC.getTableHeader().setResizingAllowed(false);
        tableHoaDon_HDPC.getTableHeader().setReorderingAllowed(false);
        scrollPaneHoaDon.setViewportView(tableHoaDon_HDPC);

        lblHoaDonChiTiet_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHoaDonChiTiet_HDPC.setText("Hóa đơn chi tiết");

<<<<<<< HEAD
        tableHoaDonChiTiet_HDPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
=======
        HoaDonChiTiet_Table.setRowHeight(25);
        HoaDonChiTiet_Table.setForeground(Color.black);
        HoaDonChiTiet_Table.setBackground(Color.WHITE);
        HoaDonChiTiet_Table.setShowGrid(true);
        HoaDonChiTiet_Table.setGridColor(Color.black);
        HoaDonChiTiet_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
>>>>>>> 9daff001e75a0a3cb54faaf95e1ffa5cd4df89e1
        ));
        tableHoaDonChiTiet_HDPC.setShowVerticalLines(true);
        tableHoaDonChiTiet_HDPC.getTableHeader().setResizingAllowed(false);
        tableHoaDonChiTiet_HDPC.getTableHeader().setReorderingAllowed(false);
        scrollPaneHoaDonChiTiet.setViewportView(tableHoaDonChiTiet_HDPC);

        panelThongTin_HDPC.setBackground(new java.awt.Color(250, 238, 232));

        lblMaHoaDon_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaHoaDon_HDPC.setText("Mã hóa đơn:");

        txtKhachHang_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblKhachHang_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang_HDPC.setText("Khách hàng:");

        lblSoDienThoai_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDienThoai_HDPC.setText("Số điện thoại:");

        lblThoiGianTao_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGianTao_HDPC.setText("Thời gian tạo:");

        lblThoiGianThanhToan_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGianThanhToan_HDPC.setText("Thời gian thanh toán:");

        lblLoaiThanhToan_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoaiThanhToan_HDPC.setText("Loại thanh toán:");

        lblGhiChu_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGhiChu_HDPC.setText("Ghi chú:");

        txtGhiChu_HDPC.setColumns(20);
        txtGhiChu_HDPC.setRows(5);
        scrollPaneGhiChu_HDPC.setViewportView(txtGhiChu_HDPC);

        javax.swing.GroupLayout panelThongTin_HDPCLayout = new javax.swing.GroupLayout(panelThongTin_HDPC);
        panelThongTin_HDPC.setLayout(panelThongTin_HDPCLayout);
        panelThongTin_HDPCLayout.setHorizontalGroup(
            panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneGhiChu_HDPC)
                    .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                        .addComponent(lblLoaiThanhToan_HDPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(txtLoaiThanhToan_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                        .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGhiChu_HDPC)
                            .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                                .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblThoiGianTao_HDPC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSoDienThoai_HDPC, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblKhachHang_HDPC)
                                    .addComponent(lblMaHoaDon_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblThoiGianThanhToan_HDPC))
                                .addGap(44, 44, 44)
                                .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaHoaDon_HDPC)
                                    .addComponent(txtKhachHang_HDPC)
                                    .addComponent(txtThoIGianTao_HDPC)
                                    .addComponent(txtSoDienThoai_HDPC, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtThoiGianThanhToan_HDPC))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelThongTin_HDPCLayout.setVerticalGroup(
            panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                        .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHoaDon_HDPC)
                            .addComponent(txtMaHoaDon_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKhachHang_HDPC)
                            .addComponent(txtKhachHang_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSoDienThoai_HDPC)
                        .addGap(18, 18, 18)
                        .addComponent(lblThoiGianTao_HDPC))
                    .addGroup(panelThongTin_HDPCLayout.createSequentialGroup()
                        .addComponent(txtSoDienThoai_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtThoIGianTao_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThoiGianThanhToan_HDPC)
                    .addComponent(txtThoiGianThanhToan_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThongTin_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiThanhToan_HDPC)
                    .addComponent(txtLoaiThanhToan_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGhiChu_HDPC)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneGhiChu_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTrangThai_HDPC.setBackground(new java.awt.Color(250, 238, 232));

        labelTrangThai_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTrangThai_HDPC.setText("Trạng thái:");

        lblTrangThai_Status_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTrangThai_Status_HDPC.setText("Chờ xác nhận");

        lblTongTienSanPham_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienSanPham_HDPC.setText("Tổng tiền sản phẩm:");

<<<<<<< HEAD
        lblChiTieuKhac_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiTieuKhac_HDPC.setText("Chi tiêu khác:");
=======

        TongTienSanPham1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TongTienSanPham1_lbl.setText("Tổng tiền sản phẩm:");
        TongTienSanPham1_lbl.setBackground(Color.white);
        TongTienSanPham1_lbl.setForeground(Color.black);

        TongTienSanPham1_txt.setBackground(Color.white);
        TongTienSanPham1_txt.setForeground(Color.black);
        TongTienSanPham1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        ChiTieuKhac1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChiTieuKhac1_lbl.setText("Chi tiêu khác:");
        ChiTieuKhac1_lbl.setBackground(Color.white);
        ChiTieuKhac1_lbl.setForeground(Color.black);

        ChiTietKhac1_txt.setBackground(Color.white);
        ChiTietKhac1_txt.setForeground(Color.black);
        ChiTietKhac1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        TongTienHoaDon1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TongTienHoaDon1_lbl.setText("Tổng tiền hóa đơn:");
        TongTienHoaDon1_lbl.setBackground(Color.white);
        TongTienHoaDon1_lbl.setForeground(Color.black);

        TongTienHoaDon1_txt.setBackground(Color.white);
        TongTienHoaDon1_txt.setForeground(Color.black);
        TongTienHoaDon1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        DiaChi1_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DiaChi1_lbl.setText("Địa chỉ:");
        DiaChi1_lbl.setBackground(Color.white);
        DiaChi1_lbl.setForeground(Color.black);

        DiaChi1_txt.setColumns(20);
        DiaChi1_txt.setRows(5);
        DiaChi1_txt.setBackground(Color.white);
        DiaChi1_txt.setForeground(Color.black);
        DiaChi1_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        scrollPaneDiaChi.setViewportView(DiaChi1_txt);
        scrollPaneDiaChi.setBackground(Color.white);

        javax.swing.GroupLayout TrangThai1Layout = new javax.swing.GroupLayout(TrangThai1);
        TrangThai1.setLayout(TrangThai1Layout);
        TrangThai1Layout.setHorizontalGroup(
                TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(TrangThai1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                                .addGap(47, 47, 47)
                                                                .addComponent(TrangThaiStatus1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(DiaChi1_lbl)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TongTienSanPham1_lbl)
                                                        .addComponent(ChiTieuKhac1_lbl)
                                                        .addComponent(TongTienHoaDon1_lbl))
                                                .addGap(39, 39, 39)
                                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TongTienSanPham1_txt)
                                                        .addComponent(ChiTietKhac1_txt)
                                                        .addComponent(TongTienHoaDon1_txt))))
                                .addContainerGap())
        );
        TrangThai1Layout.setVerticalGroup(
                TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TrangThai1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TrangThai1_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(TrangThaiStatus1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TongTienSanPham1_lbl)
                                        .addComponent(TongTienSanPham1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ChiTieuKhac1_lbl)
                                        .addComponent(ChiTietKhac1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TongTienHoaDon1_lbl)
                                        .addComponent(TongTienHoaDon1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DiaChi1_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollPaneDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        XacNhan_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        XacNhan_Button.setText("Xác nhận hóa đơn");

        XacNhan_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhan_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HoaDonPhaCheLayout = new javax.swing.GroupLayout(HoaDonPhaChe);
        HoaDonPhaChe.setLayout(HoaDonPhaCheLayout);
        HoaDonPhaCheLayout.setHorizontalGroup(
                HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(HoaDon_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HoaDonChiTiet_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211))
                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(scrollPane_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(XacNhan_Button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addComponent(ThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane_HoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HoaDonPhaCheLayout.setVerticalGroup(
                HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HoaDon_lbl)
                                        .addComponent(HoaDonChiTiet_lbl))
                                .addGap(28, 28, 28)
                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addComponent(jScrollPane_HoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(HoaDonPhaCheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ThongTin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 618, Short.MAX_VALUE))
                                        .addGroup(HoaDonPhaCheLayout.createSequentialGroup()
                                                .addComponent(scrollPane_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(XacNhan_Button)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabbedPane_HoaDon.addTab("Hóa đơn Pha chế", HoaDonPhaChe);

        LichSuHoaDon.setBackground(new java.awt.Color(250, 238, 232));

        MaHoaDon2_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaHoaDon2_lbl.setText("Mã hóa đơn:");
        MaHoaDon2_lbl.setBackground(Color.white);
        MaHoaDon2_lbl.setForeground(Color.black);

        MaHoaDon2_txt.setBackground(Color.white);
        MaHoaDon2_txt.setForeground(Color.black);
        MaHoaDon2_txt.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        Tim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tim.setText("Tìm");

        TuNgay_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TuNgay_lbl.setText("Từ ngày:");
        TuNgay_lbl.setBackground(Color.white);
        TuNgay_lbl.setForeground(Color.black);


        DenNgay_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DenNgay_lbl.setText("Đến ngày:");
        DenNgay_lbl.setBackground(Color.white);
        DenNgay_lbl.setForeground(Color.black);


        TrangThai2_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThai2_lbl.setText("Trạng thái:");
        TrangThai2_lbl.setBackground(Color.white);
        TrangThai2_lbl.setForeground(Color.black);


        cbb_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Chờ order", "Hoàn thành", " "}));
        cbb_TrangThai.setForeground(Color.black);
        cbb_TrangThai.setBackground(Color.white);

        Loc_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Loc_Button.setText("Lọc");

        HoaDonInfo_Table.setBackground(Color.white);
        HoaDonInfo_Table.setForeground(Color.black);
        HoaDonInfo_Table.setGridColor(Color.black);
        HoaDonInfo_Table.setShowGrid(true);

        HoaDonInfo_Table.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = HoaDonInfo_Table.getSelectedRow();
                String maHD = modelHoaDon.getValueAt(row, 0).toString();
                ArrayList<ChiTietHD> list = new ChiTietHD_DAO().getOrderDetail_ByID(maHD);

                modelChiTietHD.setRowCount(0);
                for (ChiTietHD cthd : list) {
                    modelChiTietHD.addRow(new Object[]{cthd.getSp().getTenSP(), cthd.getDonGia()
                            , cthd.getSoLuong(), cthd.getThanhTien(), null});
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
        HoaDonInfo_Table.setModel(modelHoaDon = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null}
                },
                new String[]{
                        "Mã hóa đơn", "Người tạo", "Khách hàng", "Thời gian tạo", "Thời gian thanh toán", "Tổng tiền", "Địa chỉ", "Trạng thái"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        HoaDonInfo_Table.setShowHorizontalLines(true);
        HoaDonInfo_Table.setShowVerticalLines(true);
        HoaDonInfo_Table.setRowHeight(25);
        scrollPaneHoaDon_LichSuHD.setViewportView(HoaDonInfo_Table);
        scrollPaneHoaDon_LichSuHD.setBackground(Color.white);

        ChiTietHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ChiTietHoaDon.setText("Chi tiết hóa đơn");
        ChiTietHoaDon.setBackground(Color.white);
        ChiTietHoaDon.setForeground(Color.black);

        jTableChiTietHD.setBackground(Color.white);
        jTableChiTietHD.setForeground(Color.black);
        jTableChiTietHD.setGridColor(Color.black);
        jTableChiTietHD.setShowGrid(true);
        jTableChiTietHD.setRowHeight(25);
        jTableChiTietHD.setModel(modelChiTietHD = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String[]{
                        "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", "Ghi chú"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        scrollPaneChiTietHoaDon.setViewportView(jTableChiTietHD);
        scrollPaneChiTietHoaDon.setBackground(Color.white);

        ThongTin2.setBackground(new java.awt.Color(250, 238, 232));

        lblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaHoaDon.setText("Mã hóa đơn:");
        lblMaHoaDon.setForeground(Color.black);
        lblMaHoaDon.setBackground(Color.white);

        txtMaHoaDon_LichSuHD.setForeground(Color.black);
        txtMaHoaDon_LichSuHD.setBackground(Color.white);
        txtMaHoaDon_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKhachHang.setText("Khách hàng:");
        lblKhachHang.setForeground(Color.black);
        lblKhachHang.setBackground(Color.white);

        txtKhachHang_LichSuHD.setForeground(Color.black);
        txtKhachHang_LichSuHD.setBackground(Color.white);
        txtKhachHang_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoDienThoai.setText("Số điện thoại:");
        lblSoDienThoai.setForeground(Color.black);
        lblSoDienThoai.setBackground(Color.white);

        txtSoDienThoai_LichSuHD.setForeground(Color.black);
        txtSoDienThoai_LichSuHD.setBackground(Color.white);
        txtSoDienThoai_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblThoiGianTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoiGianTao.setText("Thời gian tạo:");
        lblThoiGianTao.setForeground(Color.black);
        lblThoiGianTao.setBackground(Color.white);

        txtThoiGianTao_LichSuHD.setForeground(Color.black);
        txtThoiGianTao_LichSuHD.setBackground(Color.white);
        txtThoiGianTao_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblThoiGianThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoiGianThanhToan.setText("Thời gian thanh toán:");
        lblThoiGianThanhToan.setForeground(Color.black);
        lblThoiGianThanhToan.setBackground(Color.white);

        //TODO: thiếu txt thời gian thanh toán
//        thoi.setForeground(Color.black);
//        txtThoiGianTao_LichSuHD.setBackground(Color.white);
//        txtThoiGianTao_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        lblLoaiThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoaiThanhToan.setText("Loại thanh toán:");
        lblLoaiThanhToan.setForeground(Color.black);
        lblLoaiThanhToan.setBackground(Color.white);

        txtLoaiThanhToan_LichSuHD.setForeground(Color.black);
        txtLoaiThanhToan_LichSuHD.setBackground(Color.white);
        txtLoaiThanhToan_LichSuHD.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGhiChu.setText("Ghi chú:");
        lblGhiChu.setForeground(Color.black);
        lblGhiChu.setBackground(Color.white);


        textArea_GhiChu.setColumns(20);
        textArea_GhiChu.setRows(5);
        textArea_GhiChu.setForeground(Color.black);
        textArea_GhiChu.setBackground(Color.white);
        textArea_GhiChu.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        scrollPaneGhiChu_LichSuHD.setViewportView(textArea_GhiChu);

        javax.swing.GroupLayout ThongTin2Layout = new javax.swing.GroupLayout(ThongTin2);
        ThongTin2.setLayout(ThongTin2Layout);
        ThongTin2Layout.setHorizontalGroup(
                ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneGhiChu_LichSuHD)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin2Layout.createSequentialGroup()
                                                .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addComponent(txtMaHoaDon_LichSuHD))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTin2Layout.createSequentialGroup()
                                                .addComponent(lblKhachHang)
                                                .addGap(107, 107, 107)
                                                .addComponent(txtKhachHang_LichSuHD))
                                        .addComponent(lblThoiGianThanhToan)
                                        .addComponent(lblGhiChu)
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lblThoiGianTao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(97, 97, 97)
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtThoiGianTao_LichSuHD)
                                                        .addComponent(txtSoDienThoai_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addComponent(lblLoaiThanhToan)
                                                .addGap(82, 82, 82)
                                                .addComponent(txtLoaiThanhToan_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        ThongTin2Layout.setVerticalGroup(
                ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblMaHoaDon)
                                                        .addComponent(txtMaHoaDon_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblKhachHang)
                                                        .addComponent(txtKhachHang_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblSoDienThoai)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblThoiGianTao))
                                        .addGroup(ThongTin2Layout.createSequentialGroup()
                                                .addComponent(txtSoDienThoai_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtThoiGianTao_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblThoiGianThanhToan)
                                .addGap(18, 18, 18)
                                .addGroup(ThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblLoaiThanhToan)
                                        .addComponent(txtLoaiThanhToan_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblGhiChu)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneGhiChu_LichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TrangThai2.setBackground(new java.awt.Color(250, 238, 232));

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái:");
        lblTrangThai.setBackground(Color.white);
        lblTrangThai.setForeground(Color.black);

        lblTrangThai_Status.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTrangThai_Status.setText("Hoàn thành");
        lblTrangThai_Status.setForeground(Color.black);

        lblTongTienSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienSanPham.setText("Tổng tiền sản phẩm:");
        lblTongTienSanPham.setBackground(Color.white);
        lblTongTienSanPham.setForeground(Color.black);

        txt_TongTienSP.setForeground(Color.black);
        txt_TongTienSP.setBackground(Color.white);
        txt_TongTienSP.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));


        lblChiTieuKhac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiTieuKhac.setText("Chi tiêu khác:");
        lblChiTieuKhac.setBackground(Color.white);
        lblChiTieuKhac.setForeground(Color.black);

        txt_ChiTietKhac.setForeground(Color.black);
        txt_ChiTietKhac.setBackground(Color.white);
        txt_ChiTietKhac.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
>>>>>>> 9daff001e75a0a3cb54faaf95e1ffa5cd4df89e1

        lblTongTienHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienHoaDon.setText("Tổng tiền hóa đơn:");

        javax.swing.GroupLayout panelTrangThai_HDPCLayout = new javax.swing.GroupLayout(panelTrangThai_HDPC);
        panelTrangThai_HDPC.setLayout(panelTrangThai_HDPCLayout);
        panelTrangThai_HDPCLayout.setHorizontalGroup(
            panelTrangThai_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                .addGroup(panelTrangThai_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTrangThai_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTrangThai_Status_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTongTienSanPham_HDPC))
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChiTieuKhac_HDPC))
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTongTienHoaDon))
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTongTienSanPham_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTrangThai_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTongTienHoaDon_HDPC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtChiTieuKhac_HDPC, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTrangThai_HDPCLayout.setVerticalGroup(
            panelTrangThai_HDPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrangThai_HDPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTrangThai_HDPC)
                .addGap(18, 18, 18)
                .addComponent(lblTrangThai_Status_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTienSanPham_HDPC)
                .addGap(8, 8, 8)
                .addComponent(txtTongTienSanPham_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblChiTieuKhac_HDPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChiTieuKhac_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTongTienHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTienHoaDon_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btnXacNhanHoaDon_HDPC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnXacNhanHoaDon_HDPC.setText("Xác nhận hóa đơn");
        btnXacNhanHoaDon_HDPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanHoaDon_HDPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHoaDonLayout = new javax.swing.GroupLayout(panelHoaDon);
        panelHoaDon.setLayout(panelHoaDonLayout);
        panelHoaDonLayout.setHorizontalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoaDonLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblHoaDon_HDPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHoaDonChiTiet_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(panelHoaDonLayout.createSequentialGroup()
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnXacNhanHoaDon_HDPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneHoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addComponent(panelThongTin_HDPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTrangThai_HDPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        panelHoaDonLayout.setVerticalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoaDonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoaDon_HDPC)
                    .addComponent(lblHoaDonChiTiet_HDPC))
                .addGap(28, 28, 28)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addComponent(scrollPaneHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnXacNhanHoaDon_HDPC)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addComponent(scrollPaneHoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelThongTin_HDPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelTrangThai_HDPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );

        tabHoaDon.addTab("Hóa đơn Pha chế", panelHoaDon);

        panelLichSuHoaDon.setBackground(new java.awt.Color(250, 238, 232));

        lblMaHoaDonCanTim_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaHoaDonCanTim_LSHD.setText("Mã hóa đơn:");

        btnTimMaHoaDon_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimMaHoaDon_LSHD.setText("Tìm");

        lblTuNgay_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTuNgay_LSHD.setText("Từ ngày:");

        lblDenNgay_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDenNgay_LSHD.setText("Đến ngày:");

        lblTrangThai_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrangThai_LSHD.setText("Trạng thái:");

        comboBoxTrangThai_LSHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chờ order", "Hoàn thành", " " }));

        btnLoc_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoc_LSHD.setText("Lọc");

        tableHoaDonCanTim_LSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người tạo", "Khách hàng", "Thời gian tạo", "Thời gian thanh toán", "Tổng tiền", "Địa chỉ", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableHoaDonCanTim_LSHD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableHoaDonCanTim_LSHD.setDragEnabled(true);
        tableHoaDonCanTim_LSHD.setShowHorizontalLines(true);
        tableHoaDonCanTim_LSHD.setShowVerticalLines(true);
        tableHoaDonCanTim_LSHD.getTableHeader().setResizingAllowed(false);
        tableHoaDonCanTim_LSHD.getTableHeader().setReorderingAllowed(false);
        scrollPaneHoaDonCanTim_LSHD.setViewportView(tableHoaDonCanTim_LSHD);

        lblChiTietHoaDon_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChiTietHoaDon_LSHD.setText("Chi tiết hóa đơn");

        tableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableHoaDon.setShowGrid(true);
        tableHoaDon.getTableHeader().setResizingAllowed(false);
        tableHoaDon.getTableHeader().setReorderingAllowed(false);
        scrollPaneHonDon.setViewportView(tableHoaDon);

        panelThongTin_LSHD.setBackground(new java.awt.Color(250, 238, 232));

        lblMaHoaDon_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaHoaDon_LSHD.setText("Mã hóa đơn:");

        lblKhachHang_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang_LSHD.setText("Khách hàng:");

        lblSoDienThoai_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDienThoai_LSHD.setText("Số điện thoại:");

        lblThoiGianTao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGianTao.setText("Thời gian tạo:");

        lblThoiGianThanhToan_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGianThanhToan_LSHD.setText("Thời gian thanh toán:");

        lblLoaiThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoaiThanhToan.setText("Loại thanh toán:");

        lblGhiChu_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGhiChu_LSHD.setText("Ghi chú:");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        scrollPaneGhiChu.setViewportView(txtGhiChu);

        javax.swing.GroupLayout panelThongTin_LSHDLayout = new javax.swing.GroupLayout(panelThongTin_LSHD);
        panelThongTin_LSHD.setLayout(panelThongTin_LSHDLayout);
        panelThongTin_LSHDLayout.setHorizontalGroup(
            panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneGhiChu)
                    .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                        .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblThoiGianTao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSoDienThoai_LSHD, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblKhachHang_LSHD)
                            .addComponent(lblMaHoaDon_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThoiGianThanhToan_LSHD))
                        .addGap(37, 37, 37)
                        .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKhachHang_LSHD)
                            .addComponent(txtThoiGianTao_LSHD)
                            .addComponent(txtSoDienThoai_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtMaHoaDon_LSHD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtThoiGianThanhToan_LSHD)))
                    .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                        .addComponent(lblGhiChu_LSHD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                        .addComponent(lblLoaiThanhToan)
                        .addGap(73, 73, 73)
                        .addComponent(txtLoaiThanhToan)))
                .addContainerGap())
        );
        panelThongTin_LSHDLayout.setVerticalGroup(
            panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                        .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHoaDon_LSHD)
                            .addComponent(txtMaHoaDon_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKhachHang_LSHD)
                            .addComponent(txtKhachHang_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSoDienThoai_LSHD)
                        .addGap(18, 18, 18)
                        .addComponent(lblThoiGianTao))
                    .addGroup(panelThongTin_LSHDLayout.createSequentialGroup()
                        .addComponent(txtSoDienThoai_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtThoiGianTao_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThoiGianThanhToan_LSHD)
                    .addComponent(txtThoiGianThanhToan_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThongTin_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiThanhToan)
                    .addComponent(txtLoaiThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGhiChu_LSHD)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTrangThai_LSHD.setBackground(new java.awt.Color(250, 238, 232));

        lblTrangthai_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrangthai_LSHD.setText("Trạng thái:");

        lblTrangThai_Status_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTrangThai_Status_LSHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangThai_Status_LSHD.setText("Hoàn thành");

        lblTongTienSanPham_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTienSanPham_LSHD.setText("Tổng tiền sản phẩm:");

        lblChiTieuKhac_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiTieuKhac_LSHD.setText("Chi tiêu khác:");

        lblTongTIenHoaDon_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTIenHoaDon_LSHD.setText("Tổng tiền hóa đơn:");

        javax.swing.GroupLayout panelTrangThai_LSHDLayout = new javax.swing.GroupLayout(panelTrangThai_LSHD);
        panelTrangThai_LSHD.setLayout(panelTrangThai_LSHDLayout);
        panelTrangThai_LSHDLayout.setHorizontalGroup(
            panelTrangThai_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrangThai_LSHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrangThai_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrangThai_Status_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTrangThai_LSHDLayout.createSequentialGroup()
                        .addGroup(panelTrangThai_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTrangthai_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongTienSanPham_LSHD)
                            .addComponent(lblChiTieuKhac_LSHD)
                            .addComponent(txtTongTienSanPham_LSHD)
                            .addComponent(txtChiTieuKhac_LSHD)
                            .addComponent(lblTongTIenHoaDon_LSHD)
                            .addComponent(txtTongTienHoaDon_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTrangThai_LSHDLayout.setVerticalGroup(
            panelTrangThai_LSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrangThai_LSHDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrangthai_LSHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThai_Status_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTongTienSanPham_LSHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTienSanPham_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblChiTieuKhac_LSHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtChiTieuKhac_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblTongTIenHoaDon_LSHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTienHoaDon_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        btnKhoiPhucHoaDon_LSHD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnKhoiPhucHoaDon_LSHD.setText("Khôi phục hóa đơn");

        javax.swing.GroupLayout panelLichSuHoaDonLayout = new javax.swing.GroupLayout(panelLichSuHoaDon);
        panelLichSuHoaDon.setLayout(panelLichSuHoaDonLayout);
        panelLichSuHoaDonLayout.setHorizontalGroup(
            panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLichSuHoaDonLayout.createSequentialGroup()
                        .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                                .addComponent(panelThongTin_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTrangThai_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                                .addGap(535, 535, 535)
                                .addComponent(lblChiTietHoaDon_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneHonDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLichSuHoaDonLayout.createSequentialGroup()
                                .addComponent(btnKhoiPhucHoaDon_LSHD)
                                .addGap(145, 145, 145))))
                    .addComponent(scrollPaneHoaDonCanTim_LSHD)
                    .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                        .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaHoaDonCanTim_LSHD)
                            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                                .addComponent(txtMaHoaDonCanTim_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimMaHoaDon_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTuNgay_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooserTuNgay_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDenNgay_LSHD)
                            .addComponent(chooserDenNgay_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblTrangThai_LSHD))
                            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxTrangThai_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLoc_LSHD)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLichSuHoaDonLayout.setVerticalGroup(
            panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHoaDonCanTim_LSHD)
                    .addComponent(lblTuNgay_LSHD)
                    .addComponent(lblDenNgay_LSHD)
                    .addComponent(lblTrangThai_LSHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimMaHoaDon_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                        .addComponent(txtMaHoaDonCanTim_LSHD)
                        .addGap(2, 2, 2))
                    .addComponent(btnLoc_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxTrangThai_LSHD)
                    .addComponent(chooserTuNgay_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chooserDenNgay_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneHoaDonCanTim_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblChiTietHoaDon_LSHD)
                .addGap(18, 18, 18)
                .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLichSuHoaDonLayout.createSequentialGroup()
                        .addComponent(scrollPaneHonDon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKhoiPhucHoaDon_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLichSuHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelThongTin_LSHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTrangThai_LSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabHoaDon.addTab("Lịch sử hóa đơn", panelLichSuHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1278, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void btnXacNhanHoaDon_HDPCActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     


<<<<<<< HEAD
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnKhoiPhucHoaDon_LSHD;
    private javax.swing.JButton btnLoc_LSHD;
    private javax.swing.JButton btnTimMaHoaDon_LSHD;
    private javax.swing.JButton btnXacNhanHoaDon_HDPC;
    private com.toedter.calendar.JDateChooser chooserDenNgay_LSHD;
    private com.toedter.calendar.JDateChooser chooserTuNgay_LSHD;
    private javax.swing.JComboBox<String> comboBoxTrangThai_LSHD;
    private javax.swing.JLabel labelTrangThai_HDPC;
    private javax.swing.JLabel labelTrangThai_HDPC1;
    private javax.swing.JLabel lblChiTietHoaDon_LSHD;
    private javax.swing.JLabel lblChiTieuKhac_HDPC;
    private javax.swing.JLabel lblChiTieuKhac_HDPC1;
    private javax.swing.JLabel lblChiTieuKhac_LSHD;
    private javax.swing.JLabel lblDenNgay_LSHD;
    private javax.swing.JLabel lblGhiChu_HDPC;
    private javax.swing.JLabel lblGhiChu_LSHD;
    private javax.swing.JLabel lblHoaDonChiTiet_HDPC;
    private javax.swing.JLabel lblHoaDon_HDPC;
    private javax.swing.JLabel lblKhachHang_HDPC;
    private javax.swing.JLabel lblKhachHang_LSHD;
=======
    private void SoDienThoai1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoDienThoai1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoDienThoai1_txtActionPerformed

    private void loadData(ArrayList<entity.HoaDon> list) {
        modelHoaDon.setRowCount(0);
        for (entity.HoaDon hd : list) {
            modelHoaDon.addRow(new Object[]{hd.getMaHD(), hd.getNhanVien().getMaNV(), hd.getKhachHang().getSdt()
                    , hd.getNgayLapHD(), hd.getGioRa(), hd.getTongTien(), null, null});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChiTietHoaDon;
    private javax.swing.JTextField ChiTietKhac1_txt;
    private javax.swing.JLabel ChiTieuKhac1_lbl;
    private javax.swing.JLabel DenNgay_lbl;
    private javax.swing.JLabel DiaChi1_lbl;
    private javax.swing.JTextArea DiaChi1_txt;
    private javax.swing.JLabel GhiChu1_lbl;
    private javax.swing.JTextArea GhiChu1_txt;
    private javax.swing.JScrollPane scrollPane_HoaDon;
    private javax.swing.JScrollPane jScrollPane_HoaDonChiTiet;
    private javax.swing.JTable HoaDonChiTiet_Table;
    private javax.swing.JLabel HoaDonChiTiet_lbl;
    private javax.swing.JTable HoaDonInfo_Table;
    private javax.swing.JPanel HoaDonPhaChe;
    private javax.swing.JTable HoaDon_Table;
    private javax.swing.JLabel HoaDon_lbl;
    private javax.swing.JLabel KhachHang1_lbl;
    private javax.swing.JTextField KhachHang1_txt;
    private javax.swing.JPanel LichSuHoaDon;
    private javax.swing.JLabel LoaiThanhToan1_lbl;
    private javax.swing.JTextField LoaiThanhToan1_txt;
    private javax.swing.JButton Loc_Button;
    private javax.swing.JLabel MaHoaDon1_lbl;
    private javax.swing.JTextField MaHoaDon1_txt;
    private javax.swing.JLabel MaHoaDon2_lbl;
    private javax.swing.JTextField MaHoaDon2_txt;
    private javax.swing.JLabel SoDienThoai1_lbl;
    private javax.swing.JTextField SoDienThoai1_txt;
    private javax.swing.JLabel ThoiGianTao1_lbl;
    private javax.swing.JTextField ThoiGianTao1_txt;
    private javax.swing.JLabel ThoiGianThanhToan1_lbl;
    private javax.swing.JTextField ThoiGianThanhToan1_txt;
    private javax.swing.JPanel ThongTin1;
    private javax.swing.JPanel ThongTin2;
    private javax.swing.JButton Tim;
    private javax.swing.JLabel TongTienHoaDon1_lbl;
    private javax.swing.JTextField TongTienHoaDon1_txt;
    private javax.swing.JLabel TongTienSanPham1_lbl;
    private javax.swing.JTextField TongTienSanPham1_txt;
    private javax.swing.JPanel TrangThai1;
    private javax.swing.JLabel TrangThai1_lbl;
    private javax.swing.JPanel TrangThai2;
    private javax.swing.JLabel TrangThai2_lbl;
    private javax.swing.JLabel TrangThaiStatus1_lbl;
    private javax.swing.JLabel TuNgay_lbl;
    private javax.swing.JButton XacNhan_Button;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> cbb_TrangThai;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblThoiGianTao;
    private javax.swing.JLabel lblThoiGianThanhToan;
>>>>>>> 9daff001e75a0a3cb54faaf95e1ffa5cd4df89e1
    private javax.swing.JLabel lblLoaiThanhToan;
    private javax.swing.JLabel lblLoaiThanhToan_HDPC;
    private javax.swing.JLabel lblMaHoaDonCanTim_LSHD;
    private javax.swing.JLabel lblMaHoaDon_HDPC;
    private javax.swing.JLabel lblMaHoaDon_LSHD;
    private javax.swing.JLabel lblSoDienThoai_HDPC;
    private javax.swing.JLabel lblSoDienThoai_LSHD;
    private javax.swing.JLabel lblThoiGianTao;
    private javax.swing.JLabel lblThoiGianTao_HDPC;
    private javax.swing.JLabel lblThoiGianThanhToan_HDPC;
    private javax.swing.JLabel lblThoiGianThanhToan_LSHD;
    private javax.swing.JLabel lblTongTIenHoaDon_LSHD;
    private javax.swing.JLabel lblTongTienHoaDon;
    private javax.swing.JLabel lblTongTienHoaDon1;
    private javax.swing.JLabel lblTongTienSanPham_HDPC;
    private javax.swing.JLabel lblTongTienSanPham_HDPC1;
    private javax.swing.JLabel lblTongTienSanPham_LSHD;
    private javax.swing.JLabel lblTrangThai_LSHD;
    private javax.swing.JLabel lblTrangThai_Status_HDPC;
    private javax.swing.JLabel lblTrangThai_Status_HDPC1;
    private javax.swing.JLabel lblTrangThai_Status_LSHD;
    private javax.swing.JLabel lblTrangthai_LSHD;
    private javax.swing.JLabel lblTuNgay_LSHD;
    private javax.swing.JPanel panelHoaDon;
    private javax.swing.JPanel panelLichSuHoaDon;
    private javax.swing.JPanel panelThongTin_HDPC;
    private javax.swing.JPanel panelThongTin_LSHD;
    private javax.swing.JPanel panelTrangThai_HDPC;
    private javax.swing.JPanel panelTrangThai_HDPC1;
    private javax.swing.JPanel panelTrangThai_LSHD;
    private javax.swing.JScrollPane scrollPaneGhiChu;
    private javax.swing.JScrollPane scrollPaneGhiChu_HDPC;
    private javax.swing.JScrollPane scrollPaneHoaDon;
    private javax.swing.JScrollPane scrollPaneHoaDonCanTim_LSHD;
    private javax.swing.JScrollPane scrollPaneHoaDonChiTiet;
    private javax.swing.JScrollPane scrollPaneHonDon;
    private javax.swing.JTabbedPane tabHoaDon;
    private javax.swing.JTable tableHoaDon;
    private javax.swing.JTable tableHoaDonCanTim_LSHD;
    private javax.swing.JTable tableHoaDonChiTiet_HDPC;
    private javax.swing.JTable tableHoaDon_HDPC;
    private javax.swing.JTextField txtChiTieuKhac_HDPC;
    private javax.swing.JTextField txtChiTieuKhac_HDPC1;
    private javax.swing.JTextField txtChiTieuKhac_LSHD;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextArea txtGhiChu_HDPC;
    private javax.swing.JTextField txtKhachHang_HDPC;
    private javax.swing.JTextField txtKhachHang_LSHD;
    private javax.swing.JTextField txtLoaiThanhToan;
    private javax.swing.JTextField txtLoaiThanhToan_HDPC;
    private javax.swing.JTextField txtMaHoaDonCanTim_LSHD;
    private javax.swing.JTextField txtMaHoaDon_HDPC;
    private javax.swing.JTextField txtMaHoaDon_LSHD;
    private javax.swing.JTextField txtSoDienThoai_HDPC;
    private javax.swing.JTextField txtSoDienThoai_LSHD;
    private javax.swing.JTextField txtThoIGianTao_HDPC;
    private javax.swing.JTextField txtThoiGianTao_LSHD;
    private javax.swing.JTextField txtThoiGianThanhToan_HDPC;
    private javax.swing.JTextField txtThoiGianThanhToan_LSHD;
    private javax.swing.JTextField txtTongTienHoaDon_HDPC;
    private javax.swing.JTextField txtTongTienHoaDon_HDPC1;
    private javax.swing.JTextField txtTongTienHoaDon_LSHD;
    private javax.swing.JTextField txtTongTienSanPham_HDPC;
    private javax.swing.JTextField txtTongTienSanPham_HDPC1;
    private javax.swing.JTextField txtTongTienSanPham_LSHD;
    // End of variables declaration                   
}
